<?php

/**
 * @file
 * Primary module hooks for heart_diocese module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_page_attachments().
 */
function heart_diocese_page_attachments(array &$attachments) {

  // Get current path.
  $current_path = \Drupal::service('path.current')->getPath();
  $current_path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  // Add library for manage diocese.
  if ($current_path_alias == '/manage-account' || $current_path = '/node/14' || $current_path_alias == '/administrar-cuenta') {
    $attachments['#attached']['library'][] = 'heart_diocese/heart_diocese';
  }
}

/**
 * Implements hook_mail_alter().
 */
function heart_diocese_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  $headers = [
    'MIME-Version' => '1.0',
    'content-type' => 'text/html; charset=UTF-8; format=flowed; delsp=yes',
  ];
  switch ($key) {
    case 'heart_diocese_invite_user':
      foreach ($headers as $key => $value) {
        $message['headers'][$key] = $value;
      }
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);

      if (isset($params['headers'])) {
        $message['headers'] += $params['headers'];
      }

      // Render the template to HTML
      // Set up email template.
      $body_data = [
        '#theme' => 'heart_diocese_invite_user',
        '#submitted_data' => $params['message'],
      ];
      $message['body'][] = \Drupal::service('renderer')->render($body_data);

      case 'heart_parish_invite_user':
        foreach ($headers as $key => $value) {
          $message['headers'][$key] = $value;
        }
        $message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);

        if (isset($params['headers'])) {
          $message['headers'] += $params['headers'];
        }

        // Render the template to HTML
        // Set up email template.
        $body_data = [
          '#theme' => 'heart_parish_invite_user',
          '#submitted_data' => $params['message'],
        ];
        $message['body'][] = \Drupal::service('renderer')->render($body_data);

      case 'heart_class_invite_facilitator':
        foreach ($headers as $key => $value) {
          $message['headers'][$key] = $value;
        }
        $message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);

        if (isset($params['headers'])) {
          $message['headers'] += $params['headers'];
        }

        // Render the template to HTML
        // Set up email template.
        $body_data = [
          '#theme' => 'heart_class_invite_facilitator',
          '#submitted_data' => $params['message'],
        ];
        $message['body'][] = \Drupal::service('renderer')->render($body_data);

      break;
  }
}

/**
 * Implements hook_theme().
 */
function heart_diocese_theme() {
  return [
    'heart_diocese_invite_user' => [
      'template' => 'heart-diocese-invite-user',
      'variables' => ['submitted_data' => []],
    ],
    'heart_parish_invite_user' => [
      'template' => 'heart-parish-invite-user',
      'variables' => ['submitted_data' => []],
    ],
    'heart_class_invite_facilitator' => [
      'template' => 'heart-class-invite-facilitator',
      'variables' => ['submitted_data' => []],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function heart_diocese_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (isset($form['#action']) && array_key_exists('#action', $form) && $form['#action'] == '/diocese_admin_csv' && $form_id == 'views_exposed_form') {
    $form['#action'] = '';
  }
}

/**
 * Implements hook_query_alter().
 */
function heart_diocese_query_alter(Drupal\Core\Database\Query\AlterableInterface $query) {
  // Check if we are on the desired view
  if ($query->getMetaData('view') && $query->getMetaData('view')->id() === 'managing_diocese') {
    $query->groupby('heart_diocese_data_field_data.id');
  }

  if ($query->getMetaData('view') && $query->getMetaData('view')->id() === 'manage_parish') {
    $query->groupby('heart_parish_data_field_data.id');
  }

}